### ISSUE TITLE
[1.9.4] Regression: cannot get an encoder for an array of Java enums in Scala

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#155]
[Here](https://github.com/plokhotnyuk/jsoniter-scala/pull/454) is a PR that fails on CI when trying to get encoders.

The DSL-Json instance definition is:
```
val dslJson = new DslJson[Any](Settings.withRuntime().`with`(new ConfigureScala)
    .limitDigitsBuffer(Int.MaxValue /*WARNING: don't do this for open systems*/)
    .limitStringBuffer(Int.MaxValue /*WARNING: don't do this for open systems*/)
    .doublePrecision(JsonReader.DoublePrecision.EXACT))
```

An error stacktrace looks like:
```
2020-01-12T09:47:37.3634456Z [error] Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
2020-01-12T09:47:37.3636693Z [error] 	at com.dslplatform.json.runtime.ScalaClassAnalyzer$.analyzeType(ScalaClassAnalyzer.scala:229)
2020-01-12T09:47:37.3638548Z [error] 	at com.dslplatform.json.runtime.ScalaClassAnalyzer$.analyze(ScalaClassAnalyzer.scala:192)
2020-01-12T09:47:37.3640101Z [error] 	at com.dslplatform.json.runtime.ScalaClassAnalyzer$.$anonfun$Writer$1(ScalaClassAnalyzer.scala:53)
2020-01-12T09:47:37.3641549Z [error] 	at com.dslplatform.json.DslJson.lookupFromFactories(DslJson.java:1101)
2020-01-12T09:47:37.3643961Z [error] 	at com.dslplatform.json.DslJson.tryFindWriter(DslJson.java:1035)
2020-01-12T09:47:37.3646695Z [error] 	at com.dslplatform.json.runtime.ArrayAnalyzer.analyzeEncoder(ArrayAnalyzer.java:109)
2020-01-12T09:47:37.3649111Z [error] 	at com.dslplatform.json.runtime.ArrayAnalyzer.access$100(ArrayAnalyzer.java:11)
2020-01-12T09:47:37.3651607Z [error] 	at com.dslplatform.json.runtime.ArrayAnalyzer$2.tryCreate(ArrayAnalyzer.java:66)
2020-01-12T09:47:37.3654108Z [error] 	at com.dslplatform.json.runtime.ArrayAnalyzer$2.tryCreate(ArrayAnalyzer.java:59)
2020-01-12T09:47:37.3656509Z [error] 	at com.dslplatform.json.DslJson.lookupFromFactories(DslJson.java:1101)
2020-01-12T09:47:37.3659388Z [error] 	at com.dslplatform.json.DslJson.tryFindWriter(DslJson.java:1035)
2020-01-12T09:47:37.3662748Z [error] 	at com.dslplatform.json.DslJsonScala$.encoder$extension(DslJsonScala.scala:16)
2020-01-12T09:47:37.3665009Z [error] 	at com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$.codec(DslPlatformJson.scala:85)
2020-01-12T09:47:37.3666659Z [error] 	at com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$.<init>(DslPlatformJson.scala:35)
2020-01-12T09:47:37.3668833Z [error] 	at com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$.<clinit>(DslPlatformJson.scala)
2020-01-12T09:47:37.3671556Z [error] 	at com.github.plokhotnyuk.jsoniter_scala.benchmark.ListOfBooleansReading.dslJsonScala(ListOfBooleansReading.scala:28)
2020-01-12T09:47:37.3674506Z [error] 	at com.github.plokhotnyuk.jsoniter_scala.benchmark.ListOfBooleansReadingSpec.$anonfun$new$2(ListOfBooleansReadingSpec.scala:13)
```

**Comment by zapov** [comment]
Tnx for the bug report. I've fixed it in latest commit but am wondering why it doesn't fail for me in your repository. It is an actual bug but I'm unable to reproduce it by running your benchmark ;(

Can you run it with latest build (1.9.5) and let me know if there is any other issue?

**Comment by zapov** [comment]
v.1.9.5 released
