### ISSUE TITLE
[1.9.4] Unexpected runtime exception when parsing java.time.LocalTime values

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#156]
```
2020-01-12T14:18:39.6774812Z [info]   java.lang.ArrayIndexOutOfBoundsException: Index 13638 out of bounds for length 13638
2020-01-12T14:18:39.6776129Z [info]   at com.dslplatform.json.JavaTimeConverter.serialize(JavaTimeConverter.java:199)
2020-01-12T14:18:39.6777434Z [info]   at com.dslplatform.json.JavaTimeConverter.serializeNullable(JavaTimeConverter.java:107)
2020-01-12T14:18:39.6779316Z [info]   at com.dslplatform.json.JavaTimeConverter$4.write(JavaTimeConverter.java:38)
2020-01-12T14:18:39.6780893Z [info]   at com.dslplatform.json.JavaTimeConverter$4.write(JavaTimeConverter.java:35)
2020-01-12T14:18:39.6782318Z [info]   at com.dslplatform.json.runtime.ArrayEncoder.write(ArrayEncoder.java:29)
2020-01-12T14:18:39.6784164Z [info]   at com.dslplatform.json.runtime.ArrayEncoder.write(ArrayEncoder.java:5)
2020-01-12T14:18:39.6785534Z [info]   at com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$.dslJsonEncode(DslPlatformJson.scala:85)
2020-01-12T14:18:39.6786833Z [info]   at com.github.plokhotnyuk.jsoniter_scala.benchmark.ArrayOfLocalTimesWriting.dslJsonScala(ArrayOfLocalTimesWriting.scala:27)
2020-01-12T14:18:39.6788139Z [info]   at com.github.plokhotnyuk.jsoniter_scala.benchmark.ArrayOfLocalTimesWritingSpec.$anonfun$new$2(ArrayOfLocalTimesWritingSpec.scala:12)```

**Comment by zapov** [comment]
Tnx for the bug report. Fixed in latest commit.

**Comment by plokhotnyuk** [comment]
I see that [the commit](https://github.com/ngs-doo/dsl-json/commit/af7c5de0831b6e5ffe7f1abc6655fbfc3958714e) with fixes has 1.9.5 version... Will it be available on the Maven Central soon?

**Comment by zapov** [comment]
Yeah, I can release it today. It would be nice to see if there are any other things to fix before the release

**Comment by plokhotnyuk** [comment]
I had built and installed a snapshot of DSL-JSON with the latest commit, then I ran tests locally which succeeded on [this](https://github.com/plokhotnyuk/jsoniter-scala/pull/455/files) branch. Both issues reported for 1.9.4 are fixed now:
https://github.com/ngs-doo/dsl-json/issues/155
https://github.com/ngs-doo/dsl-json/issues/156

[I have a lot of others](https://github.com/plokhotnyuk/jsoniter-scala/search?q=%22FIXME%3A+DSL-JSON%22&unscoped_q=%22FIXME%3A+DSL-JSON%22) but I'm not sure it they worth to be reported.

**Comment by zapov** [comment]
v1.9.5 released on Maven
