### ISSUE TITLE
DSJ-JSON throws error for valid JSON keys with escaping

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#170]
Uncomment and run the following test to reproduce: 

https://github.com/plokhotnyuk/jsoniter-scala/blob/44b54f7543fd7100114c40049d4c243ce2799c66/jsoniter-scala-benchmark/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/ExtractFieldsReadingSpec.scala#L14 

The message:
```
{"s":"s","!!sjyehe":{"number":0.0,"boolean":false,"string":null},"!!sjyeiF":{"number":0.0,"boolean":false,"string":null},"!!sjyej'":{"number":0.0,"boolean":false,"string":null},"!!sjyfIe":{"number":0.0,"boolean":false,"string":null},"!!sjyfJF":{"number":0.0,"boolean":false,"string":null},"!!sjyfK'":{"number":0.0,"boolean":false,"string":null},"!!sjyg*e":{"number":0.0,"boolean":false,"string":null},"!!sjyg+F":{"number":0.0,"boolean":false,"string":null},"!!sjyg,'":{"number":0.0,"boolean":false,"string":null},"!!sjzFhe":{"number":0.0,"boolean":false,"string":null},"!!sjzFiF":{"number":0.0,"boolean":false,"string":null},"!!sjzFj'":{"number":0.0,"boolean":false,"string":null},"!!sjzGIe":{"number":0.0,"boolean":false,"string":null},"!!sjzGJF":{"number":0.0,"boolean":false,"string":null},"!!sjzGK'":{"number":0.0,"boolean":false,"string":null},"!!sjzH*e":{"number":0.0,"boolean":false,"string":null},"!!sjzH+F":{"number":0.0,"boolean":false,"string":null},"!!sjzH,'":{"number":0.0,"boolean":false,"string":null},"!!sj{'he":{"number":0.0,"boolean":false,"string":null},"!!sj{'iF":{"number":0.0,"boolean":false,"string":null},"!!sj{'j'":{"number":0.0,"boolean":false,"string":null},"!!sj{(Ie":{"number":0.0,"boolean":false,"string":null},"!!sj{(JF":{"number":0.0,"boolean":false,"string":null},"!!sj{(K'":{"number":0.0,"boolean":false,"string":null},"!!sj{)*e":{"number":0.0,"boolean":false,"string":null},"!!sj{)+F":{"number":0.0,"boolean":false,"string":null},"!!sj{),'":{"number":0.0,"boolean":false,"string":null},"!!skZehe":{"number":0.0,"boolean":false,"string":null},"!!skZeiF":{"number":0.0,"boolean":false,"string":null},"!!skZej'":{"number":0.0,"boolean":false,"string":null},"!!skZfIe":{"number":0.0,"boolean":false,"string":null},"!!skZfJF":{"number":0.0,"boolean":false,"string":null},"!!skZfK'":{"number":0.0,"boolean":false,"string":null},"!!skZg*e":{"number":0.0,"boolean":false,"string":null},"!!skZg+F":{"number":0.0,"boolean":false,"string":null},"!!skZg,'":{"number":0.0,"boolean":false,"string":null},"!!sk[Fhe":{"number":0.0,"boolean":false,"string":null},"!!sk[FiF":{"number":0.0,"boolean":false,"string":null},"!!sk[Fj'":{"number":0.0,"boolean":false,"string":null},"!!sk[GIe":{"number":0.0,"boolean":false,"string":null},"!!sk[GJF":{"number":0.0,"boolean":false,"string":null},"!!sk[GK'":{"number":0.0,"boolean":false,"string":null},"!!sk[H*e":{"number":0.0,"boolean":false,"string":null},"!!sk[H+F":{"number":0.0,"boolean":false,"string":null},"!!sk[H,'":{"number":0.0,"boolean":false,"string":null},"!!sk\\'he":{"number":0.0,"boolean":false,"string":null},"!!sk\\'iF":{"number":0.0,"boolean":false,"string":null},"!!sk\\'j'":{"number":0.0,"boolean":false,"string":null},"!!sk\\(Ie":{"number":0.0,"boolean":false,"string":null},"!!sk\\(JF":{"number":0.0,"boolean":false,"string":null},"!!sk\\(K'":{"number":0.0,"boolean":false,"string":null},"!!sk\\)*e":{"number":0.0,"boolean":false,"string":null},"!!sk\\)+F":{"number":0.0,"boolean":false,"string":null},"!!sk\\),'":{"number":0.0,"boolean":false,"string":null},"!!sl;ehe":{"number":0.0,"boolean":false,"string":null},"!!sl;eiF":{"number":0.0,"boolean":false,"string":null},"!!sl;ej'":{"number":0.0,"boolean":false,"string":null},"!!sl;fIe":{"number":0.0,"boolean":false,"string":null},"!!sl;fJF":{"number":0.0,"boolean":false,"string":null},"!!sl;fK'":{"number":0.0,"boolean":false,"string":null},"!!sl;g*e":{"number":0.0,"boolean":false,"string":null},"!!sl;g+F":{"number":0.0,"boolean":false,"string":null},"!!sl;g,'":{"number":0.0,"boolean":false,"string":null},"!!sl<Fhe":{"number":0.0,"boolean":false,"string":null},"!!sl<FiF":{"number":0.0,"boolean":false,"string":null},"!!sl<Fj'":{"number":0.0,"boolean":false,"string":null},"!!sl<GIe":{"number":0.0,"boolean":false,"string":null},"!!sl<GJF":{"number":0.0,"boolean":false,"string":null},"!!sl<GK'":{"number":0.0,"boolean":false,"string":null},"!!sl<H*e":{"number":0.0,"boolean":false,"string":null},"!!sl<H+F":{"number":0.0,"boolean":false,"string":null},"!!sl<H,'":{"number":0.0,"boolean":false,"string":null},"!!sl='he":{"number":0.0,"boolean":false,"string":null},"!!sl='iF":{"number":0.0,"boolean":false,"string":null},"!!sl='j'":{"number":0.0,"boolean":false,"string":null},"!!sl=(Ie":{"number":0.0,"boolean":false,"string":null},"!!sl=(JF":{"number":0.0,"boolean":false,"string":null},"!!sl=(K'":{"number":0.0,"boolean":false,"string":null},"!!sl=)*e":{"number":0.0,"boolean":false,"string":null},"!!sl=)+F":{"number":0.0,"boolean":false,"string":null},"!!sl=),'":{"number":0.0,"boolean":false,"string":null},"!!tKyehe":{"number":0.0,"boolean":false,"string":null},"!!tKyeiF":{"number":0.0,"boolean":false,"string":null},"!!tKyej'":{"number":0.0,"boolean":false,"string":null},"!!tKyfIe":{"number":0.0,"boolean":false,"string":null},"!!tKyfJF":{"number":0.0,"boolean":false,"string":null},"!!tKyfK'":{"number":0.0,"boolean":false,"string":null},"!!tKyg*e":{"number":0.0,"boolean":false,"string":null},"!!tKyg+F":{"number":0.0,"boolean":false,"string":null},"!!tKyg,'":{"number":0.0,"boolean":false,"string":null},"!!tKzFhe":{"number":0.0,"boolean":false,"string":null},"!!tKzFiF":{"number":0.0,"boolean":false,"string":null},"!!tKzFj'":{"number":0.0,"boolean":false,"string":null},"!!tKzGIe":{"number":0.0,"boolean":false,"string":null},"!!tKzGJF":{"number":0.0,"boolean":false,"string":null},"!!tKzGK'":{"number":0.0,"boolean":false,"string":null},"!!tKzH*e":{"number":0.0,"boolean":false,"string":null},"!!tKzH+F":{"number":0.0,"boolean":false,"string":null},"!!tKzH,'":{"number":0.0,"boolean":false,"string":null},"!!tK{'he":{"number":0.0,"boolean":false,"string":null},"!!tK{'iF":{"number":0.0,"boolean":false,"string":null},"!!tK{'j'":{"number":0.0,"boolean":false,"string":null},"!!tK{(Ie":{"number":0.0,"boolean":false,"string":null},"!!tK{(JF":{"number":0.0,"boolean":false,"string":null},"!!tK{(K'":{"number":0.0,"boolean":false,"string":null},"!!tK{)*e":{"number":0.0,"boolean":false,"string":null},"!!tK{)+F":{"number":0.0,"boolean":false,"string":null},"!!tK{),'":{"number":0.0,"boolean":false,"string":null},"!!tLZehe":{"number":0.0,"boolean":false,"string":null},"!!tLZeiF":{"number":0.0,"boolean":false,"string":null},"!!tLZej'":{"number":0.0,"boolean":false,"string":null},"!!tLZfIe":{"number":0.0,"boolean":false,"string":null},"!!tLZfJF":{"number":0.0,"boolean":false,"string":null},"!!tLZfK'":{"number":0.0,"boolean":false,"string":null},"!!tLZg*e":{"number":0.0,"boolean":false,"string":null},"!!tLZg+F":{"number":0.0,"boolean":false,"string":null},"!!tLZg,'":{"number":0.0,"boolean":false,"string":null},"!!tL[Fhe":{"number":0.0,"boolean":false,"string":null},"!!tL[FiF":{"number":0.0,"boolean":false,"string":null},"!!tL[Fj'":{"number":0.0,"boolean":false,"string":null},"!!tL[GIe":{"number":0.0,"boolean":false,"string":null},"!!tL[GJF":{"number":0.0,"boolean":false,"string":null},"!!tL[GK'":{"number":0.0,"boolean":false,"string":null},"!!tL[H*e":{"number":0.0,"boolean":false,"string":null},"!!tL[H+F":{"number":0.0,"boolean":false,"string":null},"!!tL[H,'":{"number":0.0,"boolean":false,"string":null},"!!tL\\'he":{"number":0.0,"boolean":false,"string":null},"!!tL\\'iF":{"number":0.0,"boolean":false,"string":null},"!!tL\\'j'":{"number":0.0,"boolean":false,"string":null},"!!tL\\(Ie":{"number":0.0,"boolean":false,"string":null},"!!tL\\(JF":{"number":0.0,"boolean":false,"string":null},"!!tL\\(K'":{"number":0.0,"boolean":false,"string":null},"!!tL\\)*e":{"number":0.0,"boolean":false,"string":null},"!!tL\\)+F":{"number":0.0,"boolean":false,"string":null},"!!tL\\),'":{"number":0.0,"boolean":false,"string":null},"!!tM;ehe":{"number":0.0,"boolean":false,"string":null},"!!tM;eiF":{"number":0.0,"boolean":false,"string":null},"!!tM;ej'":{"number":0.0,"boolean":false,"string":null},"!!tM;fIe":{"number":0.0,"boolean":false,"string":null},"!!tM;fJF":{"number":0.0,"boolean":false,"string":null},"!!tM;fK'":{"number":0.0,"boolean":false,"string":null},"!!tM;g*e":{"number":0.0,"boolean":false,"string":null},"!!tM;g+F":{"number":0.0,"boolean":false,"string":null},"!!tM;g,'":{"number":0.0,"boolean":false,"string":null},"!!tM<Fhe":{"number":0.0,"boolean":false,"string":null},"!!tM<FiF":{"number":0.0,"boolean":false,"string":null},"!!tM<Fj'":{"number":0.0,"boolean":false,"string":null},"!!tM<GIe":{"number":0.0,"boolean":false,"string":null},"!!tM<GJF":{"number":0.0,"boolean":false,"string":null},"!!tM<GK'":{"number":0.0,"boolean":false,"string":null},"!!tM<H*e":{"number":0.0,"boolean":false,"string":null},"!!tM<H+F":{"number":0.0,"boolean":false,"string":null},"!!tM<H,'":{"number":0.0,"boolean":false,"string":null},"!!tM='he":{"number":0.0,"boolean":false,"string":null},"!!tM='iF":{"number":0.0,"boolean":false,"string":null},"!!tM='j'":{"number":0.0,"boolean":false,"string":null},"!!tM=(Ie":{"number":0.0,"boolean":false,"string":null},"!!tM=(JF":{"number":0.0,"boolean":false,"string":null},"!!tM=(K'":{"number":0.0,"boolean":false,"string":null},"!!tM=)*e":{"number":0.0,"boolean":false,"string":null},"!!tM=)+F":{"number":0.0,"boolean":false,"string":null},"!!tM=),'":{"number":0.0,"boolean":false,"string":null},"!!u,yehe":{"number":0.0,"boolean":false,"string":null},"!!u,yeiF":{"number":0.0,"boolean":false,"string":null},"!!u,yej'":{"number":0.0,"boolean":false,"string":null},"!!u,yfIe":{"number":0.0,"boolean":false,"string":null},"!!u,yfJF":{"number":0.0,"boolean":false,"string":null},"!!u,yfK'":{"number":0.0,"boolean":false,"string":null},"!!u,yg*e":{"number":0.0,"boolean":false,"string":null},"!!u,yg+F":{"number":0.0,"boolean":false,"string":null},"!!u,yg,'":{"number":0.0,"boolean":false,"string":null},"!!u,zFhe":{"number":0.0,"boolean":false,"string":null},"!!u,zFiF":{"number":0.0,"boolean":false,"string":null},"!!u,zFj'":{"number":0.0,"boolean":false,"string":null},"!!u,zGIe":{"number":0.0,"boolean":false,"string":null},"!!u,zGJF":{"number":0.0,"boolean":false,"string":null},"!!u,zGK'":{"number":0.0,"boolean":false,"string":null},"!!u,zH*e":{"number":0.0,"boolean":false,"string":null},"!!u,zH+F":{"number":0.0,"boolean":false,"string":null},"!!u,zH,'":{"number":0.0,"boolean":false,"string":null},"!!u,{'he":{"number":0.0,"boolean":false,"string":null},"!!u,{'iF":{"number":0.0,"boolean":false,"string":null},"!!u,{'j'":{"number":0.0,"boolean":false,"string":null},"!!u,{(Ie":{"number":0.0,"boolean":false,"string":null},"!!u,{(JF":{"number":0.0,"boolean":false,"string":null},"!!u,{(K'":{"number":0.0,"boolean":false,"string":null},"!!u,{)*e":{"number":0.0,"boolean":false,"string":null},"!!u,{)+F":{"number":0.0,"boolean":false,"string":null},"!!u,{),'":{"number":0.0,"boolean":false,"string":null},"!!u-Zehe":{"number":0.0,"boolean":false,"string":null},"!!u-ZeiF":{"number":0.0,"boolean":false,"string":null},"!!u-Zej'":{"number":0.0,"boolean":false,"string":null},"!!u-ZfIe":{"number":0.0,"boolean":false,"string":null},"!!u-ZfJF":{"number":0.0,"boolean":false,"string":null},"!!u-ZfK'":{"number":0.0,"boolean":false,"string":null},"!!u-Zg*e":{"number":0.0,"boolean":false,"string":null},"!!u-Zg+F":{"number":0.0,"boolean":false,"string":null},"!!u-Zg,'":{"number":0.0,"boolean":false,"string":null},"!!u-[Fhe":{"number":0.0,"boolean":false,"string":null},"!!u-[FiF":{"number":0.0,"boolean":false,"string":null},"!!u-[Fj'":{"number":0.0,"boolean":false,"string":null},"!!u-[GIe":{"number":0.0,"boolean":false,"string":null},"!!u-[GJF":{"number":0.0,"boolean":false,"string":null},"!!u-[GK'":{"number":0.0,"boolean":false,"string":null},"!!u-[H*e":{"number":0.0,"boolean":false,"string":null},"!!u-[H+F":{"number":0.0,"boolean":false,"string":null},"!!u-[H,'":{"number":0.0,"boolean":false,"string":null},"!!u-\\'he":{"number":0.0,"boolean":false,"string":null},"!!u-\\'iF":{"number":0.0,"boolean":false,"string":null},"!!u-\\'j'":{"number":0.0,"boolean":false,"string":null},"!!u-\\(Ie":{"number":0.0,"boolean":false,"string":null},"!!u-\\(JF":{"number":0.0,"boolean":false,"string":null},"!!u-\\(K'":{"number":0.0,"boolean":false,"string":null},"!!u-\\)*e":{"number":0.0,"boolean":false,"string":null},"!!u-\\)+F":{"number":0.0,"boolean":false,"string":null},"!!u-\\),'":{"number":0.0,"boolean":false,"string":null},"!!u.;ehe":{"number":0.0,"boolean":false,"string":null},"!!u.;eiF":{"number":0.0,"boolean":false,"string":null},"!!u.;ej'":{"number":0.0,"boolean":false,"string":null},"!!u.;fIe":{"number":0.0,"boolean":false,"string":null},"!!u.;fJF":{"number":0.0,"boolean":false,"string":null},"!!u.;fK'":{"number":0.0,"boolean":false,"string":null},"!!u.;g*e":{"number":0.0,"boolean":false,"string":null},"!!u.;g+F":{"number":0.0,"boolean":false,"string":null},"!!u.;g,'":{"number":0.0,"boolean":false,"string":null},"!!u.<Fhe":{"number":0.0,"boolean":false,"string":null},"!!u.<FiF":{"number":0.0,"boolean":false,"string":null},"!!u.<Fj'":{"number":0.0,"boolean":false,"string":null},"!!u.<GIe":{"number":0.0,"boolean":false,"string":null},"!!u.<GJF":{"number":0.0,"boolean":false,"string":null},"!!u.<GK'":{"number":0.0,"boolean":false,"string":null},"!!u.<H*e":{"number":0.0,"boolean":false,"string":null},"!!u.<H+F":{"number":0.0,"boolean":false,"string":null},"!!u.<H,'":{"number":0.0,"boolean":false,"string":null},"!!u.='he":{"number":0.0,"boolean":false,"string":null},"!!u.='iF":{"number":0.0,"boolean":false,"string":null},"!!u.='j'":{"number":0.0,"boolean":false,"string":null},"!!u.=(Ie":{"number":0.0,"boolean":false,"string":null},"!!u.=(JF":{"number":0.0,"boolean":false,"string":null},"!!u.=(K'":{"number":0.0,"boolean":false,"string":null},"!!u.=)*e":{"number":0.0,"boolean":false,"string":null},"!!u.=)+F":{"number":0.0,"boolean":false,"string":null},"!!u.=),'":{"number":0.0,"boolean":false,"string":null},"!\"Tjyehe":{"number":0.0,"boolean":false,"string":null},"!\"TjyeiF":{"number":0.0,"boolean":false,"string":null},"!\"Tjyej'":{"number":0.0,"boolean":false,"string":null},"!\"TjyfIe":{"number":0.0,"boolean":false,"string":null},"!\"TjyfJF":{"number":0.0,"boolean":false,"string":null},"!\"TjyfK'":{"number":0.0,"boolean":false,"string":null},"!\"Tjyg*e":{"number":0.0,"boolean":false,"string":null},"!\"Tjyg+F":{"number":0.0,"boolean":false,"string":null},"!\"Tjyg,'":{"number":0.0,"boolean":false,"string":null},"!\"TjzFhe":{"number":0.0,"boolean":false,"string":null},"!\"TjzFiF":{"number":0.0,"boolean":false,"string":null},"!\"TjzFj'":{"number":0.0,"boolean":false,"string":null},"!\"TjzGIe":{"number":0.0,"boolean":false,"string":null},"!\"TjzGJF":{"number":0.0,"boolean":false,"string":null},"!\"TjzGK'":{"number":0.0,"boolean":false,"string":null},"!\"TjzH*e":{"number":0.0,"boolean":false,"string":null},"!\"TjzH+F":{"number":0.0,"boolean":false,"string":null},"!\"TjzH,'":{"number":0.0,"boolean":false,"string":null},"!\"Tj{'he":{"number":0.0,"boolean":false,"string":null},"!\"Tj{'iF":{"number":0.0,"boolean":false,"string":null},"!\"Tj{'j'":{"number":0.0,"boolean":false,"string":null},"!\"Tj{(Ie":{"number":0.0,"boolean":false,"string":null},"!\"Tj{(JF":{"number":0.0,"boolean":false,"string":null},"!\"Tj{(K'":{"number":0.0,"boolean":false,"string":null},"!\"Tj{)*e":{"number":0.0,"boolean":false,"string":null},"!\"Tj{)+F":{"number":0.0,"boolean":false,"string":null},"!\"Tj{),'":{"number":0.0,"boolean":false,"string":null},"!\"TkZehe":{"number":0.0,"boolean":false,"string":null},"!\"TkZeiF":{"number":0.0,"boolean":false,"string":null},"!\"TkZej'":{"number":0.0,"boolean":false,"string":null},"!\"TkZfIe":{"number":0.0,"boolean":false,"string":null},"!\"TkZfJF":{"number":0.0,"boolean":false,"string":null},"!\"TkZfK'":{"number":0.0,"boolean":false,"string":null},"!\"TkZg*e":{"number":0.0,"boolean":false,"string":null},"!\"TkZg+F":{"number":0.0,"boolean":false,"string":null},"!\"TkZg,'":{"number":0.0,"boolean":false,"string":null},"!\"Tk[Fhe":{"number":0.0,"boolean":false,"string":null},"!\"Tk[FiF":{"number":0.0,"boolean":false,"string":null},"!\"Tk[Fj'":{"number":0.0,"boolean":false,"string":null},"!\"Tk[GIe":{"number":0.0,"boolean":false,"string":null},"!\"Tk[GJF":{"number":0.0,"boolean":false,"string":null},"!\"Tk[GK'":{"number":0.0,"boolean":false,"string":null},"!\"Tk[H*e":{"number":0.0,"boolean":false,"string":null},"!\"Tk[H+F":{"number":0.0,"boolean":false,"string":null},"!\"Tk[H,'":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\'he":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\'iF":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\'j'":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\(Ie":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\(JF":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\(K'":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\)*e":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\)+F":{"number":0.0,"boolean":false,"string":null},"!\"Tk\\),'":{"number":0.0,"boolean":false,"string":null},"!\"Tl;ehe":{"number":0.0,"boolean":false,"string":null},"!\"Tl;eiF":{"number":0.0,"boolean":false,"string":null},"!\"Tl;ej'":{"number":0.0,"boolean":false,"string":null},"i":1}
```
Full stack trace
```
Expecting ':' after attribute name. Found T at position: 13649, following: `"string":null},"!\"T`, before: `jyehe":{"number":0.0`
com.dslplatform.json.ParsingException: Expecting ':' after attribute name. Found T at position: 13649, following: `"string":null},"!\"T`, before: `jyehe":{"number":0.0`
	at com.dslplatform.json.ParsingException.create(ParsingException.java:16)
	at com.dslplatform.json.JsonReader.newParseError(JsonReader.java:416)
	at com.dslplatform.json.JsonReader.newParseError(JsonReader.java:404)
	at com.dslplatform.json.JsonReader.fillName(JsonReader.java:870)
	at com.dslplatform.json.runtime.ImmutableDescription.readObjectSlow(ImmutableDescription.java:112)
	at com.dslplatform.json.runtime.ImmutableDescription.read(ImmutableDescription.java:76)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$.dslJsonDecode(DslPlatformJson.scala:79)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.ExtractFieldsReading.dslJsonScala(ExtractFieldsReading.scala:54)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.ExtractFieldsReadingSpec.$anonfun$new$2(ExtractFieldsReadingSpec.scala:14)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1879)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
	at org.scalatest.wordspec.AnyWordSpec.run(AnyWordSpec.scala:1879)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

**Comment by zapov** [comment]
Tnx for the bug report.
Fixed in latest commit

**Comment by plokhotnyuk** [comment]
Fixed in: https://github.com/ngs-doo/dsl-json/commit/a5e5403e6ab6c41a8ee863b27514bcecc7248fb1
