### ISSUE TITLE
Boolean conversion for String "true" and "false"

### ISSUE THREAD

**Issue by prasannajoshi2121** [ngs-doo/dsl-json#188]
Hi @zapov ,

DSL library is not able to parse "true" or "false" string value as boolean or Boolean type. getting following error while deserialising json. 

com.dslplatform.json.ParsingException: Found invalid boolean value at position: 18, following: `{"primitve_type":"`, before: `true"}`

as code is already generated , not able to use custom Serializer/Deserialzer. Please let me know if this can be fixed ?? :)

as always attached reproducible example.  

[dslissue.zip](https://github.com/ngs-doo/dsl-json/files/5395529/dslissue.zip)

**Comment by zapov** [comment]
If you attach custom property converter that will surely work: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L40
Not sure about custom type converter: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L182
That might work, its worth to try

**Comment by prasannajoshi2121** [comment]
it seems like working for reference type but NOT for primitive (boolean.class) type. 

As for primitive boolean type , we can't use type parameter in Read and Write Object.

following is compiler time error : 

Fatal error compiling: java.lang.ClassCastException: com.sun.tools.javac.code.Type$JCPrimitiveType cannot be cast to javax.lang.model.type.DeclaredType.


for below snippet.

@JsonConverter(target = boolean.class)
  public static abstract class booleanConverter {
    public static final JsonReader.ReadObject<Boolean> JSON_READER = reader -> {
      if (reader.wasNull()) return false;
      Boolean b = Boolean.valueOf(reader.readSimpleString());
      return b;
    };
    public static final JsonWriter.WriteObject<Boolean> JSON_WRITER = (writer, value) -> {
      if (value == null) {
        writer.writeNull();
      } else {
        writer.writeString(value.toString());
      }
    };
  }

**Comment by prasannajoshi2121** [comment]
@zapov 
also i cant change from boolean to Boolean as entire code is having boolean with  isGetter() methods , so changing to Boolean would require replacing all isGetter occurrences with normal Getter method.

**Comment by zapov** [comment]
Added support for primitives in latest commit

**Comment by prasannajoshi2121** [comment]
thank you very much let me test

**Comment by prasannajoshi2121** [comment]
Hi @zapov ,

thanks for quick fix , having following issues :

1. Not able to create two custom convertors ,
 @JsonConverter(target = boolean.class) and @JsonConverter(target = Boolean.class) ,  getting following compilation error in my workspace , but was able to compile in your DSL project without any issue. Tried  manually adding CLC.jar dependency also in my workspace but no luck.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project dsl-issue: Compilation failure
[ERROR] Failed creating compiled json serialization file dsl_json.java.lang._Integer_DslJsonConverter
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project dsl-issue: Compilation failure
Failed creating compiled json serialization file dsl_json.java.lang._Integer_DslJsonConverter

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
Failed creating compiled json serialization file dsl_json.java.lang._Integer_DslJsonConverter

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1161)
	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:176)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more

2. As I am unable to create two convertors , at any given time boolean or Boolean only works but not both together.

let me know what could be the issue.

**Comment by prasannajoshi2121** [comment]
I guess you are not getting compilation error due to - <compilerArgument>-proc:none</compilerArgument> this

**Comment by zapov** [comment]
Pushed a fix for this to support both types at the same time

**Comment by prasannajoshi2121** [comment]
@zapov thank you very much for quick support , tested and working as per expectation. Closing issue.

**Comment by prasannajoshi2121** [comment]
Just let me know once its  available in Maven Central .
