### ISSUE TITLE
Serialization / Deserialization Problem

### ISSUE THREAD

**Issue by FlooIG** [ngs-doo/dsl-json#196]
Hello, 
I would like to parse a String in int to be able to deserialize with DLS Json but it makes me a mistake?
Can you tell me how to do it ?
Sincerely
Flo'

Error : 

Exception in thread "main" com.dslplatform.json.ParsingException: Expecting '"' for string start. Found [ at position: 1, following: `[`, before: `34, `
                at com.dslplatform.json.ParsingException.create(ParsingException.java:16)
                at com.dslplatform.json.JsonReader.newParseError(JsonReader.java:420)
                at com.dslplatform.json.JsonReader.newParseError(JsonReader.java:408)
                at com.dslplatform.json.JsonReader.parseString(JsonReader.java:642)
                at com.dslplatform.json.JsonReader.readString(JsonReader.java:624)
                at com.dslplatform.json.StringConverter$1.read(StringConverter.java:15)
                at com.dslplatform.json.StringConverter$1.read(StringConverter.java:10)
                at com.dslplatform.json.DslJson.deserialize(DslJson.java:1573)
                at Test.main(Test.java:25)

Code : 

public static void main(String[] args) throws IOException {
    DslJson<Object> dslJson = new DslJson<>();
    JsonWriter writer = dslJson.newWriter();
    dslJson.serialize(writer, "Hey");
    byte[] buffer = writer.getByteBuffer();
    int size = writer.size();

    String test = Arrays.toString(buffer) + ":" + size;
    String[] test1 = test.split(":");

    byte[] buffer1 = test1[0].getBytes();
    int size1 = Integer.parseInt(test1[1]);

    String testClass = dslJson.deserialize(String.class, buffer1, size1);
    System.out.println(testClass);
}

**Comment by zapov** [comment]
You have bugs in your code which you should fix.
dsl-json is telling you that it can't parse string containing [ and missing quote

I suggest printlining arguments which you send to dsl-json to see what you are trying to parse. Also, size argument should be related to the buffer.
