### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by centratelemedia** [ngs-doo/dsl-json#241]
using gson this working fine, but error using dsl-json

```
{"id_user":"-1","nopol":"dfas","imei":"ds","phone":"ds","id_gpsbrand":"261","id_vhbrand":"","object_type":0,"icon":"car.png","install_date":"2022-12-30","guaranty_date":"2022-12-21"}

```

error

```
om.dslplatform.json.ParsingException: Expecting '"' for string start. Found 0 at position: 107, following: `":"","object_type":0`, before: `,"icon":"car.png","i`
	at com.dslplatform.json.ParsingException.create(ParsingException.java:16)
	at com.dslplatform.json.JsonReader.newParseError(JsonReader.java:420)
	at com.dslplatform.json.JsonReader.newParseError(JsonReader.java:408)
	at com.dslplatform.json.JsonReader.parseString(JsonReader.java:642)
	at com.dslplatform.json.JsonReader.readString(JsonReader.java:624)
	at com.dslplatform.json.StringConverter$1.read(StringConverter.java:15)
	at com.dslplatform.json.StringConverter$1.read(StringConverter.java:10)
```

**Comment by zapov** [comment]
I'm assuming this is some unrelated setup error. Since there was no clarification I'll close it
