### ISSUE TITLE
Question: Testing File Read with dsl-json

### ISSUE THREAD

**Issue by nsnyder1992** [ngs-doo/dsl-json#253]
Hi I am looking to persist some json documents to a file on a low memory device. I would just use an embedded database like ObjectDB, but the document must be encrypted at rest, and I have yet to find an embedded database that does this. Also I do not need a full database for what I am doing so it seems overkill to include one. 

I have tried gson using their streaming api, https://sites.google.com/site/gson/streaming, but it was way too slow. So I found dsl-json and I already see a great deal of performance increase. But I would like to use the dsl JsonReader so that if I give it a path `$.nodes.1.services.1.parameters.num` it will give me the value at that path. I already did this with the gson streaming api, and saw even better preformance, so I'm hoping to use the same concept here. Here is what I have so far with the dsl-json implementation (I have negated some of the logic to make things simpler):

```
   @Test
   public void testDslEncryption() throws FileNotFoundException, IOException
   {
        String[] path = pathStr.split("\\.");
        start = System.currentTimeMillis();
        try(FileChannel channel = FileChannel.open(Paths.get(filePath), StandardOpenOption.READ);
                CipherInputStream cin = new CipherInputStream(Channels.newInputStream(channel), cipher);)
        {
            com.dslplatform.json.JsonReader<Object> reader = dslJson.newReader(cin, new byte[2048]);
            
            Integer value = getDslValue(reader, path, Integer.class);
            System.out.println("VALUE: " + value);
        }
        System.out.println("dsl stream encrypted read: " + (System.currentTimeMillis() - start));
    }

 public <T> String getDslValue(com.dslplatform.json.JsonReader<Object> reader, 
                         String[] path, Class<T> clazz) throws IOException
    {
        boolean isObject = false;
        
        int pathIndex = 0;
        
        while(reader.getCurrentIndex() < reader.length())
        {
            byte b =  reader.getNextToken();
            switch(b)
            {
                case '{':
                    isObject=true;
                    break;
                case '}':
                    break;
                case '[':
                    isObject=false;
                    break;
                case ']':
                case ':':
                case ',':
                    break;
                case '\"':
                    if (isObject)
                    {
                        String key = reader.readKey();
                        if (path[pathIndex].equals(key))
                        {
                            if (pathIndex == path.length - 1)
                            {
                                return  reader.next(clazz);
                            }
                            
                            pathIndex++;
                            break;
                        }
                        reader.skip();
                        break;
                    }      
                    break;
                default:
                    break;
            }
        }
        
        return null;
    }
```

The simplified json in the document is: 
```
{
   "nodes": {
       "1": {
           "services":{
               "1":{
                    "parameters":{
                        "num":1,
                        "text":"Hi 1"
                    }
               }
       }
   }
}
```

But I noticed that when `reader.readKey()` is called it moves past the '1' value, putting `reader.last() = 1`, and then the `reader.nextToken() = ,`, leading to the following (truncated) error: 
```
com.dslplatform.json.ParsingException: Error parsing number at position: 172, following: `olean":false,"num":1`, before: `,"text":"Hello 1","m`
	at com.dslplatform.json.ParsingException.create(ParsingException.java:16)
	at com.dslplatform.json.JsonReader.newParseErrorAt(JsonReader.java:450)
	at com.dslplatform.json.NumberConverter.parseNumberGeneric(NumberConverter.java:323)
	at com.dslplatform.json.NumberConverter.parsePositiveInt(NumberConverter.java:945)
	at com.dslplatform.json.NumberConverter.deserializeInt(NumberConverter.java:932)
	at com.dslplatform.json.NumberConverter$12.read(NumberConverter.java:117)
	at com.dslplatform.json.NumberConverter$12.read(NumberConverter.java:113)
	at com.dslplatform.json.JsonReader.next(JsonReader.java:1464)
	at com.accruent.service.db.DslTest.getDslValue(DslTest.java:158)
	at com.accruent.service.db.DslTest.testEncryption(DslTest.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at ...
```

I switched to the path `$.nodes.1.services.1.parameters.text` and the return statement to `return reader.readString()` and I get the correct value of 'Hi 1'. But using `reader.next(clazz)' where `clazz = String.class`, yields a similar error as above. I don't think I totally understand how the `reader.next(clazz)` works. 

Is there a way to move the reader back by 1, so that `reader.last() = :`, and then the `reader.nextToken() = 1`? Would this make `reader.next(clazz) = 1` as well?

Would I need to make a class that implements the ReadObject interface, maybe?

If someone could point me in the right direction, it would be greatly appreciated :)

**Comment by zapov** [comment]
The basic idea was that it positions you on the start of the next token. So you can check what kind of token that is by doing `last()`
