### ISSUE TITLE
Fails to parse valid JSON

### ISSUE THREAD

**Issue by martin-g** [ngs-doo/dsl-json#39]
I'm trying to parse JSON like:

```json
{
  "success": 1,
  "return": {
    "343152": {
      "pair": "abcd",
      "type": "xyz",
      "start_amount": 13.345,
      "amount": 12.345,
      "rate": 485,
      "timestamp_created": 1342448420,
      "status": 0
    }
  }
}
```

But it fails with: 
```
Exception in thread "main" java.io.IOException: Unexpected end of JSON input
	at com.dslplatform.json.JsonReader.read(JsonReader.java:292)
	at com.dslplatform.json.JsonReader.getNextToken(JsonReader.java:684)
	at com.dslplatform.json.ObjectConverter.deserializeMap(ObjectConverter.java:122)
	at com.dslplatform.json.ObjectConverter$4.read(ObjectConverter.java:31)
	at com.dslplatform.json.ObjectConverter$4.read(ObjectConverter.java:28)
	at com.dslplatform.json.DslJson.deserialize(DslJson.java:1263)
	at com.example.Test.main(Test.java:16)
```

I've tried to simplify the JSON to find what exactly causes the problem to:
```json
{
  "a": 1,
  "b": {
    "c": {
      "d": "e"
    }
  }
}
```

but now it fails with:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.<init>(String.java:196)
	at com.dslplatform.json.DslJson$SimpleStringCache.createAndPut(DslJson.java:539)
	at com.dslplatform.json.DslJson$SimpleStringCache.get(DslJson.java:530)
	at com.dslplatform.json.JsonReader.readKey(JsonReader.java:929)
	at com.dslplatform.json.ObjectConverter.deserializeMap(ObjectConverter.java:120)
	at com.dslplatform.json.ObjectConverter.deserializeObject(ObjectConverter.java:87)
	at com.dslplatform.json.ObjectConverter.deserializeMap(ObjectConverter.java:125)
	at com.dslplatform.json.ObjectConverter$4.read(ObjectConverter.java:31)
	at com.dslplatform.json.ObjectConverter$4.read(ObjectConverter.java:28)
	at com.dslplatform.json.DslJson.deserialize(DslJson.java:1263)
	at com.example.Test.main(Test.java:16)
```

My Java code is :
```java
String json = "<ONE OF THE ABOVE SNIPPETS>";
DslJson<Object> dsl = new DslJson<>();
final Map deserialize = dsl.deserialize(Map.class, json.getBytes(StandardCharsets.UTF_8), 16);
System.err.println("des\n" + deserialize);
```

**Comment by zapov** [comment]
Why do you pass 16 as length instead of actual string length in utf8 bytes?

**Comment by zapov** [comment]
btw. tnx for the bug report regarding StringIndexOutOfBoundsException. That's an unexpected exception which is now fixed.

btw2. the reason why there is no deserialize(Class, String) API is to discourage use of String. But I guess I could provide helper method for input bytes without asking for length

**Comment by martin-g** [comment]
Actually in my application I used the InputStream version and it failed the
same way as with the original/longer JSON.

**Comment by martin-g** [comment]
I'll prepare another test case.

**Comment by martin-g** [comment]
It appeared to be a small typo in the JSON that caused the original problem.
Everything works just fine now!
