### ISSUE TITLE
Uppercase keys cause JSON de-seralisation issues

### ISSUE THREAD

**Issue by lwis** [ngs-doo/dsl-json#70]
```kotlin
package application

import com.dslplatform.json.CompiledJson
import com.dslplatform.json.DslJson
import com.dslplatform.json.JsonAttribute
import com.dslplatform.json.runtime.Settings

@CompiledJson
data class Response(@JsonAttribute(name = "QueryResult") val queryResult: QueryResult?)

data class QueryResult(@JsonAttribute(name = "PageSize") val pageSize: Int?)

fun main(args: Array<String>) {
    //include service loader will load up classes created via annotation processor
    val dslJson = DslJson<Any>(Settings.withRuntime<Any>().includeServiceLoader())

    val jsonNotWorking = "{\"QueryResult\": {\"PageSize\": 200}}"
    println(dslJson.deserialize(Response::class.java, jsonNotWorking.byteInputStream()))

    val jsonWorking = "{\"queryResult\": {\"pageSize\": 200}}"
    println(dslJson.deserialize(Response::class.java, jsonWorking.byteInputStream()))
}
```

Output
```
Response(queryResult=null)
Response(queryResult=QueryResult(pageSize=200))
```

Using the above example, when the JSON contains CamelCase keys the JSON de-serialisation fails.

**Comment by lwis** [comment]
Moreover, I see;

```
Exception in thread "main" java.io.IOException: Unable to find reader for provided type: class application.Response and fallback serialization is not registered.
Try initializing DslJson with custom fallback in case of unsupported objects or register specified type using registerReader into class com.dslplatform.json.DslJson
	at com.dslplatform.json.DslJson.createErrorMessage(DslJson.java:1582)
	at com.dslplatform.json.DslJson.deserialize(DslJson.java:1897)
	at com.dslplatform.json.DslJson.deserialize(DslJson.java:1844)
	at application.ReproKt.main(Repro.kt:18)
```

If I change `val queryResult: QueryResult?` to `val QueryResult: QueryResult?`

**Comment by zapov** [comment]
Interestingly this works in Java.
I'll have to setup Kotlin project with tests to replicate it....

Do you want to help with setting up project for testing Kotlin stuff?

**Comment by lwis** [comment]
@zapov Sure, I've adapted the example Kotlin code within the project;

```
import com.dslplatform.json.CompiledJson
import com.dslplatform.json.DslJson
import com.dslplatform.json.JsonAttribute
import com.dslplatform.json.runtime.Settings
import java.io.ByteArrayOutputStream

//annotation processor will run for the specified data class
//if annotation is missing and it's not accessed through some other object with annotation
//class will be analyzed at runtime
@CompiledJson
data class DataClass(@JsonAttribute(alternativeNames = ["Language"]) val language: String,
                     @JsonAttribute(alternativeNames = ["Versions"]) val versions: List<Int>,
                     @JsonAttribute(alternativeNames = ["Library"]) val library: String,
                     @JsonAttribute(alternativeNames = ["NestedClass"]) val nestedClass: NestedClass)

data class NestedClass(@JsonAttribute(alternativeNames = ["Number"]) val number: Int)

fun main(args: Array<String>) {
    //include service loader will load up classes created via annotation processor
    val dslJson = DslJson<Any>(Settings.withRuntime<Any>().includeServiceLoader())
    val dc = DataClass(language = "Kotlin", versions = listOf(170, 171, 172), library = "DSL-JSON", nestedClass = NestedClass(1))
    val output = ByteArrayOutputStream()
    dslJson.serialize(dc, output)

    println(output.toString(Charsets.UTF_8.name()))

    println(dslJson.deserialize(DataClass::class.java, output.toByteArray().inputStream()))

    val testString = "{\"Language\":\"Kotlin\",\"Versions\":[170,171,172],\"Library\":\"DSL-JSON\",\"NestedClass\":{\"Number\":1}}"

    println(dslJson.deserialize(DataClass::class.java, testString.byteInputStream()))
}
```

Once again, switching *any* field name to CamelCase (e.g. `val Language: String`) causes an exception during initialisation.

**Comment by zapov** [comment]
I tried your example but it works fine for me.

So I would guess that you haven't setup the kapt to do the annotation processing part and thus it's falling back to reflection. 

Can you check if you have `generated/source/kapt/main/dsl_json_Annotation_Processor_External_Serialization` ?

**Comment by zapov** [comment]
@lwis did you managed to resolve this?

**Comment by lwis** [comment]
Unfortunately not, however I'm not sure if it's my setup - I'll close this for now until I get some more time to look into it.

**Comment by lwis** [comment]
@zapov unfortuantely the issue still persists with capitalised keys.

**Comment by zapov** [comment]
Can you put a sample project here?

**Comment by lwis** [comment]
I tried it against the code I wrote before (above) which was adapted to your Kotlin example. Simply capitalizing the input JSON keys will break it.

**Comment by lwis** [comment]
Nice 🎉

**Comment by zapov** [comment]
v1.8.3 released
